services:
  db:
    container_name: vyybe_db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vyybe
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: vyybe_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vyybe.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db

  server:
    container_name: vyybe_server
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: backend/server:latest
    ports:
      - "8081:8081"

volumes:
 pgdata: